[project]
name = "trial-ragas-llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ragas>=0.2.14",
    "sacrebleu>=2.5.1",
    "unstructured[md]>=0.17.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
